### ISSUE TITLE
AccessToken was never null

### ISSUE THREAD

**Issue by brandonduchesne** [jcoliz/PlaidQuickstartBlazor#1]
Cloned the repo set my ClientID and Secret and ran the server. After clicking the link button, `context.Credentials?.AccessToken is null` was never true and would skip over the method and set context.LinkSuccess to true. Not sure if I missed a step?

**Comment by jcoliz** [comment]
Hi, thanks for reporting. I will have a look!

**Comment by jcoliz** [comment]
@brandonduchesne That is strange. You're sure you did not set an access token in the secrets.yaml or anywhere else?

```yaml
Plaid:
# Get your Plaid API keys from the dashboard: https://dashboard.plaid.com/account/keys
  ClientID: (something)
  Secret: (something)
  Environment: Sandbox
  AccessToken: (something) <-- Problem would occur if you have something here
```

Please set a breakpoint on Link.razor:53 and report the contents of context.Credentials?.AccessToken, thanks! If it looks like a valid value, e.g. "access-sandbox-(something)", then the config is picking up an access token from somewhere.
